'use client';
import { useEffect, useState } from 'react';
import { CalendarDays, CheckCircle2, ChevronDown, ExternalLink, FileText, Newspaper, ClipboardList } from 'lucide-react';

const plan = [
  ['Eylül 2026','Brifing ve mentör ekibi kurulumu','Mentör adaylarını belirleme, kurs hazırlığı ve dormant takip başlangıcı.',[
    ['1–4 Eylül','Dönem başlangıç dosyası','Önceki planın kapanışı, tamamlanan işler ve devredilecek ihtiyaçlar; il brifingi veri başlıkları.','Kapanış dosyası, başlangıç veri listesi ve gerekçeli devir tablosu.','Bu bölümde gönderim yok; gerçekleşme ayrıca teyit edilir.'],
    ['7–11 Eylül','İl brifingi, ihtiyaç ve iletişim hazırlığı','Okul destek talepleri, ilçe iletişimleri, dormant çalışma listesi ve iki kursun hazırlık dosyası. İl brifingi 11 Eylül’de sunulur.','İl brifingi, doğrulanacak okul/hesap listesi, kurs programı ve eğitici belgesi kontrolü.','7 Eylül uyum ve hazırlık; 11 Eylül il brifingi.'],
    ['14–18 Eylül','Mentör ekibinin belirlenmesi ve tanışma toplantısı','Aktif ve deneyimli gönüllü adayların proje bilgisi ve uygunluğu teyit edilir. 18 Eylül 20.00’de Teams toplantısı yapılır.','İlçe bazlı mentör listesi, katılım ve görev paylaşım notları, dormant başlangıç sayımları.','Aday bilgileri 14 Eylül’de gözden geçirilir.'],
    ['21–25 Eylül','Kurs onayı ve eTwinning ile Okula Dönüş webinar serisi','İki kursun onay, mekân ve katılımcı işlemleri; 21–23 Eylül 20.00’de üç Teams oturumu ve mentör tanıtımı.','Kurs listeleri, dergi şablonu, webinar duyurusu, katılım listeleri ve rehberlik notları.','21 Eylül’de program, mekân, görevlendirme ve belge kontrolü.'],
    ['28–30 Eylül','Proje başlangıç rehberliği','Proje tasarımı, ilk kursun teknik hazırlığı, dormant/mükerrer kayıt teyitleri ve mentör görev paylaşımı.','Proje taslakları, eylül özeti, hesap takip listesi ve görev paylaşımı taslağı.','Yakın ilçe ziyaretleri talep ve hava koşuluna göre.']]],
  ['Ekim 2026','Kurslar ve koordinatörler çalıştayı','Kurslar: 5–9 ve 19–23 Ekim; çalıştay: 14–16 Ekim, Gaziantep; ITE iş birliği.',[
    ['1–2 Ekim','Proje başlangıç rehberliği (devam)','Proje görüşmeleri, kurs hazırlığı, hesap teyitleri ve ilçe mentör ekibinin görev paylaşımı.','Proje taslakları, eylül özeti, hesap takip listesi ve mentör görev taslağı.','Bu bölümde gönderim yok.'],
    ['5–9 Ekim','Yüz yüze eğitim — Seri 1','Eğitimde Yeni Yaklaşımlar Kursu, 30 ders saati.','Devam ve değerlendirme kayıtları; ders etkinliği ve proje taslağı.','Kesin tarih; rutin ziyaret yükü azaltılır.'],
    ['12–16 Ekim','İl koordinatörleri, ekipler ve ITE çalıştayı','14–16 Ekim Gaziantep çalıştayı; 12–13 Ekim hazırlık.','Program, katılım kaydı ve Erzurum’a aktarılacak karar/uygulama notları.','Katılım resmî liste ve görevlendirmeye bağlıdır.'],
    ['19–23 Ekim','Yüz yüze eğitim — Seri 2','Aynı 30 saatlik kursun ikinci gruba uygulanması.','İkinci grup çıktıları ve iki grup için ayrı başarı/katılım özeti.','Kesin tarih; ikinci öğretmen grubu.'],
    ['26–30 Ekim','Mentör koordinasyonu ve ITE görüşmesi','Mentörlerle yüz yüze koordinasyon; Eğitim Fakültesine ITE iş birliği talebi.','Karar notları, görev çizelgesi, ilçe destek takvimi ve izin dosyası hazırlığı.','26 Ekim fakülte görüşmesi; 28 Ekim yalnız sabah.']]],
  ['Kasım 2026','Eğitim, izin ve uygulama takibi','Webinarlar, kurs sonrası destek, rektörlük izni ve tören hazırlığı.',[
    ['2–6 Kasım','Webinar 2 ve rektörlük izin başvurusu','Dijital araçlarla öğrenci iş birliği ve ortak ürün webinarı; ITE izin talebi.','Ortak ürün örneği, izin talebi ve başvuru takip kaydı.','İzin sonuçlanmadan öğrenci etkinliği yapılmaz.'],
    ['9–13 Kasım','Webinar 3 ve uygulama takibi','Ölçme-değerlendirme ve proje kanıtı; Seri 1 uygulama takibi.','Ölçme aracı, uygulama örnekleri, izin durumu ve tören ilk listesi.','Dördüncü webinar 23–27 Kasım.'],
    ['16–20 Kasım','Ara tatil — masa başı değerlendirme','Geri bildirimler ve uygulama örnekleri; randevulu kısa çevrim içi destek.','Eksik/ertelemeli işler, dergi içerik havuzu ve duyuru izleme notu.','Ara tatilde masa başı işler sürer.'],
    ['23–27 Kasım','Webinar 4, uygulama ve tören hazırlığı','Bütünlüklü proje planı ve akran geri bildirimi; Seri 2 ve mentör değerlendirmesi.','Revize taslaklar, kasım özeti, tören listesi ve ITE sonucu.','Son webinar ve kurs takibi.'],
    ['30 Kasım','Etiket takdim töreni — son hazırlık','Davet, program, erişim, oturma, imza ve görsel kayıt sorumluları.','Onaylı program, katılım planı ve görev dağılımı.','Teyitli liste ve uygulama günü hazırlanır.']]],
  ['Aralık 2026','Etiket töreni, ITE ve ara değerlendirme','Takdim töreni, üniversite iş birliği ve proje ara değerlendirmesi.',[
    ['1–4 Aralık','Tören son hazırlığı (devam)','Davet, program, erişim ve görevlerin kesinleştirilmesi.','Kesin uygulama günü, program ve katılım planı.','Bu bölümde gönderim yok.'],
    ['7–11 Aralık','2026 Kalite Etiketi ve eTwinning Okulu Etiketleri Takdim Töreni','İl genelindeki hak sahipleri için tek il töreni ve iyi uygulama paylaşımı.','Katılım dağılımı, teslim belgeleri, haber bağlantıları, fotoğraflar ve etkinlik raporu.','Öncelikli tören haftası; sonuç, belge ve salona bağlı.'],
    ['14–18 Aralık','ITE — sonbahar buluşması','İzin sonrası Eğitim Fakültesiyle tanıtım ve örnek proje etkinliği.','Teyitli program, izin, katılım ve bahar taslakları.','İzin yoksa ertelenir.'],
    ['21–25 Aralık','Proje ara değerlendirmesi','İlk öğrenci ortak ürünleri, hedef/iş birliği/değerlendirme uyumu ve yardım masası.','Gelişim notları, dergi seçkisi ve destek listesi.','Kış koşullarında çevrim içi destek öncelikli.'],
    ['28–31 Aralık','Yıl sonu değerlendirmesi','Mentör değerlendirmesi, raporların tamamlanması ve bahar ihtiyaçları.','Aralık özeti ve hedef–gerçekleşme karşılaştırması.','Tören yapıldıysa ocakta tekrarlanmaz.']]],
  ['Ocak 2027','İlk dönem kapanışı','Tören yedeği, proje değerlendirmesi ve yarıyıl arşivi.',[
    ['4–8 Ocak','Tören yedeği / proje yardım masası','Aralıkta yapılamayan tören; tamamlandıysa proje yardım masası.','Tören raporu veya rehberlik kayıtları.','Tek törenin yedeğidir.'],['11–15 Ocak','İlk dönem sonuçlarını toplama','Kurs uygulamaları, okul talepleri, okul etiketi çağrısı ve dormant durumlar.','Uygulama örnekleri, ihtiyaçlar ve brifing göstergeleri.','2027 çağrısı güncel ölçütlerle izlenir.'],['18–22 Ocak','Birinci dönem kapanışı','Mentör değerlendirmesi ve şubat destek takvimi.','Ocak özeti, devir listesi, dergi paketi ve dönem brifingi.','Gerçekleşmeyen işler gerekçesiyle devredilir.'],['25–29 Ocak','Yarıyıl tatili — arşiv düzeni','Rapor, bağlantı ve dosya bütünlüğü; dergi ön incelemesi.','Dijital arşiv, eksik kanıt listesi ve yeni tarihler.','Masa başı ve idari takip.']]],
  ['Şubat 2027','İkinci dönem','Okul ekipleri, güncel çağrılar ve başvuru yardım masası.',[
    ['1–5 Şubat','Bahar hazırlığı','ITE, sergi ve kalite etiketi hazırlığı; resmî çağrılar.','Bahar destek takvimi ve güncellenecek rehber.','Yarıyıl tatilinde hazırlık.'],['8–12 Şubat','İkinci dönem koordinasyonu','Mentörlerle çevrim içi açılış ve okul ihtiyaçları.','Destek öncelikleri, randevular ve dormant takip notu.','Webinar saati katılımcılara göre.'],['15–19 Şubat','Okul etiketi ve proje desteği','Liderlik, iş birliği, kanıt düzeni ve güncel başvuru adımları.','Okul kontrolü, eksik kanıtlar ve aday çalışmalar.','Resmî çağrıya göre yürütülür.'],['22–26 Şubat','Birebir başvuru yardım masası','Okul/öğretmen görüşmeleri ve bahar ITE teyidi.','Görüşme kayıtları, şubat özeti ve ITE programı.','İzin kapsamı kontrol edilir.']]],
  ['Mart 2027','ITE ve sergi hazırlığı','Üniversite atölyesi, okul talepleri ve öğrenci ortak ürünleri.',[
    ['1–5 Mart','Ara tatil öncesi proje kontrolü','Çağrı kontrolü ve sergi ölçütleri.','Destek sonuçları, talep listesi ve ortak ürün örnekleri.','Son tarih resmî duyurudan alınır.'],['8–12 Mart','Ara tatil ve Ramazan Bayramı','Arşiv, duyuru kontrolü ve randevu düzeni.','Güncel iş listesi ve arşiv.','8 Mart yalnız sabah.'],['15–19 Mart','Sergi çağrısı ve saha desteği','Sergi çağrısı; talep ve hava koşuluna göre ziyaret.','Başvuru şablonu, ihtiyaçlar, ziyaret notları ve izinler.','Saha rotası koşullara göre.'],['22–26 Mart','ITE — bahar atölyesi','İzin sonrası ortak ders/proje etkinliği.','Etkinlik taslakları, eşleştirme önerileri ve geri bildirim.','5–9 Nisan yedek pencere.'],['29–31 Mart','Mart değerlendirmesi ve sergi tasarımı','Sergi adayları, proje ihtiyaçları ve hesap takip listesi.','Sergi taslağı, mart özeti ve dergi seçkisi.','Yeni kalite etiketi kılavuzu kontrolü.']]],
  ['Nisan 2027','Kalite etiketi rehberliği','Proje kanıtları, birebir destek ve sergi seçkisi.',[
    ['1–2 Nisan','Mart değerlendirmesi (devam)','Sergi adayları, ITE ürünleri ve hesap listesi.','Sergi taslağı ve mart özeti.','Bu bölümde gönderim yok.'],['5–9 Nisan','Kalite etiketi rehberliği','İl geneli webinar ve ölçüt eşleştirmesi.','Kanıt kontrol listesi ve iyileştirme planları.','Güncel kılavuza göre.'],['12–16 Nisan','Sergi hazırlığı ve okul rehberliği','Aday çalışmalar, randevulu destek ve ziyaret.','Geliştirilen dosyalar, ihtiyaçlar ve yazı taslakları.','Ziyaret ve oda desteği ayrı kaydedilir.'],['19–22 Nisan','Öğrenci ürünleri ve sergi seçkisi','Ortak ürünlerin şeffaf ölçütlerle seçimi.','Ön liste, açıklamalar, izin ve eksik belge listesi.','23 Nisan çizelge dışı.'],['26–30 Nisan','Nisan kapanışı ve sergi lojistiği','Ulaşım, mekân, görev, hesap ihtiyaçları ve dergi yazıları.','Nisan özeti, görev planı ve teyitli liste.','Yer ve izinler teyit edilir.']]],
  ['Mayıs 2027','Paylaşım ve il sergisi','eTwinning Günü dijital vitrini ve 24–28 Mayıs il sergisi.',[
    ['3–7 Mayıs','eTwinning Günü — dijital proje vitrini','Okullardan proje tanıtımı/ürün/video; 7 Mayıs çevrim içi vitrin.','Katılım listesi, vitrin bağlantısı, haberler ve içerik havuzu.','Hafta içi yürütülür.'],['10–14 Mayıs','Sergi son hazırlığı','Ürün, teknik ekipman, ulaşım ve görev kontrolleri.','Son kontrol listesi ve okul eksikleri.','Başvuru desteği randevuyla.'],['20–21 Mayıs','Bayram haftası — sınırlı takip','Sergi son teyitleri ve acil sorular.','Teyitler ve çözülemeyen ihtiyaçlar.','Toplu etkinlik yok.'],['24–28 Mayıs','İl eTwinning proje sergisi','Öğrenci ortak ürünleri; uzak ilçeler için dijital katılım.','Katalog, okul/proje/katılımcı sayıları, görseller ve haberler.','Kesin gün, mekân ve ulaşım teyit edilir.'],['31 Mayıs','Kalite etiketi başvuru destek haftası','Kanıt inceleme, webinar/yardım masası ve okul eksikleri.','Başvuru kontrolü, destek notları ve dergi içerikleri.','Güncel resmî takvime göre.']]],
  ['Haziran 2027','Başvuru ve yıl sonu','Kalite etiketi desteği, dergi teslimi ve eğitim yılı kapanışı.',[
    ['1–4 Haziran','Kalite etiketi desteği (devam)','Proje kanıtları ve okul bazlı eksikler.','Başvuru kontrolü ve içerikler.','Bu bölümde gönderim yok.'],['7–11 Haziran','Birebir kalite etiketi desteği','Öğretmenin kendi katkısına yönelik başvuru rehberliği.','Görüşme kayıtları ve tamamlanacak kanıtlar.','Başvuru kopyalanmaz.'],['14–18 Haziran','Dergi içerik teslimi ve son kontroller','Metin/görsellerin toplanması ve başvuru desteği.','Teslim çizelgesi, izinler ve yıl sonu göstergeleri.','Tatil öncesi tamamlanır.'],['21–25 Haziran','Eğitim yılı kapanışı','Mentör değerlendirmesi, açık sorular ve içerik havuzu.','Haziran özeti, dönem brifingi ve devir işleri.','25 Haziran ders yılı sonu.'],['28–30 Haziran','Son başvuru takibi / yayın dosyası','Takvime göre son destek veya dergi editörlüğü.','Takip listesi, editöryal dosya ve eylül ihtiyaçları.','Yalnız güncel resmî takvime göre.']]],
  ['Temmuz 2027','Dergi hazırlığı','Metin düzenleme, kaynak kontrolü, sayfa tasarımı ve ilk prova.',[
    ['1–2 Temmuz','Yayın dosyası (devam)','Başvuru takibi veya editöryal hazırlık.','Takip listesi ve editöryal dosya.','Bu bölümde gönderim yok.'],['5–9 Temmuz','Dergi editörlüğü','Bölüm sırası, dil, görsel, kaynak ve katkı sahipleri.','İlk düzenleme ve izin eksik listesi.','Masa başı editörlük.'],['12–16 Temmuz','Dergi doğrulaması','Kaynak, okul adı, tarih ve sayı kontrolü.','Doğrulanmış metinler ve düzeltme listesi.','15 Temmuz çizelge dışı.'],['19–23 Temmuz','Dergi sayfa tasarımı','İçeriklerin sayfa düzeni ve kaynak gösterimi.','İlk mizanpaj, içindekiler ve künye.','İzinler kontrol edilir.'],['26–30 Temmuz','Temmuz kapanışı ve ilk prova','İlk bütüncül prova ve takip sonuçları.','Temmuz notu, prova düzeltmeleri ve ağustos listesi.','Plan, gerçekleşme sayılmaz.']]],
  ['Ağustos 2027','Yayın ve dönem devri','Dormant durum yenileme, yıllık dergi yayını ve arşiv kapanışı.',[
    ['2–6 Ağustos','Dormant durum yenileme','Hesap listesi, çözülen/bekleyen/teyit gereken kayıtlar.','Hesap izleme, mükerrer adayları ve ikinci prova.','Birleştirme/silme için teyit gerekir.'],['9–13 Ağustos','Yayın incelemesi ve erişilebilirlik','İmla, görsel, bağlantı ve erişilebilirlik kontrolü.','Yayıma hazır metinler ve izin listesi.','Kurumsal inceleme yapılır.'],['16–20 Ağustos','Yayın son hazırlığı','Son prova, dağıtım/haber metni ve dönem brifingi.','Yayın dosyası, kalıcı erişim ve öncelik listesi.','Son prova tamamlanır.'],['23–27 Ağustos','Yıllık derginin yayımlanması','2026–2027 yıllık sayısının dijital yayını ve duyurusu.','Kalıcı bağlantı, yayın haberi ve rapor kayıtları.','Yayın hedef penceresi kesindir.'],['31 Ağustos','Dönem devri ve arşiv kapanışı','Gerçekleşme özeti, gerekçeli devir ve arşivin sabitlenmesi.','Kapanış dosyası, brifing verileri ve devir planı.','30 Ağustos hariç; 31 Ağustos kapanış.']]],
];

const REPORT_KEY='refika-plan-report-queue';
const readQueue=()=>{try{return JSON.parse(localStorage.getItem(REPORT_KEY)||'[]')}catch{return []}};

export function PlanReportQueue({ onOpen }) {
 const [queue,setQueue]=useState([]);
 useEffect(()=>setQueue(readQueue()),[]);
 return <section className="card plan-queue"><div className="card-heading"><h2><ClipboardList/> Dönem raporu hazırlık listesi</h2><span className="badge">{queue.length} faaliyet</span></div>{queue.length?<><p>Faaliyet kaydı ve haber bilgileri tamamlandıktan sonra bu çalışmalar dönem raporunda kullanılacak.</p><ul>{queue.map(item=><li key={item.id}><div><b>{item.title}</b><small>{item.month} · {item.date}</small></div><span>Rapor için işaretlendi</span></li>)}</ul>{onOpen&&<button className="secondary" onClick={()=>onOpen('Faaliyet Planı')}>Faaliyet planını aç</button>}</>:<div className="empty">Faaliyet planından dönem raporu için işaretlenmiş çalışma yok.</div>}</section>
}

export default function ActivityPlan({ onOpen }) {
 const [open,setOpen]=useState('Eylül 2026');
 const [done,setDone]=useState({});
 const [queue,setQueue]=useState([]);
 useEffect(()=>setQueue(readQueue()),[]);
 const mark=(month,i,step,item)=>{setDone(v=>({...v,[`${month}-${i}`]:step}));if(step==='report'){const row={id:`${month}-${i}`,month,date:item[0],title:item[1]};setQueue(current=>{const next=current.some(x=>x.id===row.id)?current:[...current,row];localStorage.setItem(REPORT_KEY,JSON.stringify(next));return next;});}};
 const openActivity=(month,i,item,mode)=>{
  localStorage.setItem('refika-plan-draft',JSON.stringify({id:`${month}-${i}`,month,dateRange:item[0],title:item[1],mode}));
  setDone(v=>({...v,[`${month}-${i}`]:mode}));
  onOpen?.('Raporlar ve Yazışmalar');
 };
 return <section className="activity-plan">
  <header className="plan-hero"><div><span className="eyebrow">2026–2027 · Erzurum</span><h1>İl Koordinatörü Faaliyet Planı</h1><p>YEĞİTEK Faaliyet Planı kaydındaki aylık çalışmalar, beklenen çıktılar ve uygulama notları.</p><a className="plan-official-link" href="https://yegitek.eba.gov.tr/etwinning-rapor/" target="_blank" rel="noreferrer">YEĞİTEK eTwinning Rapor Modülünü aç <ExternalLink/></a></div><span>{plan.length} ay · {plan.reduce((n,m)=>n+m[3].length,0)} çalışma</span></header>
  <div className="plan-rule"><CalendarDays/><div><b>Haftalık sabit çalışma</b><p>Her pazartesi validasyon talepleri kontrol edilir. Resmî tatilde ilk iş gününe aktarılır; yalnız hazır ve teyitli talepler gönderime hazırlanır.</p></div></div>
  <div className="plan-months">{plan.map(([month,theme,summary,items])=><article className="plan-month card" key={month}>
   <button className="plan-month-head" onClick={()=>setOpen(open===month?'':month)} aria-expanded={open===month}><div><small>{month}</small><h2>{theme}</h2><p>{summary}</p></div><ChevronDown className={open===month?'turned':''}/></button>
   {open===month&&<div className="plan-items">{items.map((item,i)=>{const status=done[`${month}-${i}`]||'planned'; const queued=queue.some(x=>x.id===`${month}-${i}`); return <section className="plan-item" key={item[0]}><div className="plan-date">{item[0]}</div><div className="plan-main"><h3>{item[1]}</h3><p>{item[2]}</p><dl><dt>Beklenen çıktı</dt><dd>{item[3]}</dd><dt>Uygulama notu</dt><dd>{item[4]}</dd></dl><div className="plan-flow"><button className={status==='record'?'active':''} onClick={()=>openActivity(month,i,item,'record')}><ClipboardList/> Faaliyet kaydı oluştur</button><button className={status==='news'?'active':''} onClick={()=>openActivity(month,i,item,'news')}><Newspaper/> Haberi hazırla</button><button className={queued?'active':''} onClick={()=>mark(month,i,'report',item)}><FileText/> Rapor hazırlık listesine ekle</button>{queued&&<span><CheckCircle2/> Rapor hazırlık listesine eklendi</span>}</div></div></section>})}</div>}
  </article>)}</div>
  <PlanReportQueue />
  <section className="card plan-reporting"><h2>Dönem raporlama takvimi</h2><p>Rapor, planlanan işler üzerinden değil; gerçekleşen faaliyet, gerçek katılım, kanıt, haber bağlantısı ve varsa imza/katılım belgesi üzerinden hazırlanır.</p><div className="report-periods">{[['2025–2026 / 3. Dönem','01.07–30.09.2026','Eylül başlangıç çalışmaları'],['2025–2026 / 4. Dönem','01.10–31.12.2026','Kurslar, çalıştay, mentörlük ve rehberlik'],['2026–2027 / 1. Dönem','01.01–31.03.2027','Proje, ITE, ziyaret ve başvuru desteği'],['2026–2027 / 2. Dönem','01.04–30.06.2027','eTwinning Günü, sergi ve kalite etiketi'],['2026–2027 / 3. Dönem','01.07–30.09.2027','Dergi, arşiv ve dönem devri'],['2026–2027 / 4. Dönem','01.10–31.12.2027','Yeni dönem faaliyetleri, izleme ve yıl sonu raporlaması']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span><p>{x[2]}</p></div>)}</div><button className="primary" onClick={()=>onOpen('Raporlar ve Yazışmalar')}>Rapor hazırlık listesini aç <FileText/></button></section>
  <details className="card plan-principles"><summary>Uygulama esasları</summary><p>Yürütücü Erzurum eTwinning İl Koordinatörüdür. Mentörler, güncel proje çalışmaları ve gönüllülükleri teyit edilerek ilçe bazında belirlenir. Kurs günleri kesindir; diğer günler ilgili kurumlarla teyit edilir.</p><p>ITE çalışmaları Eğitim Fakültesi iş birliği ve rektörlük izninden sonra başlar. Validasyonda onay, düzeltme, birleştirme ve silme ayrı izlenir. Planlanan faaliyet gerçekleşmiş sayılmaz; tamamlanmayan işler gerekçe ve yeni zamanlamayla devredilir.</p></details>
 </section>
}
