'use client';
import { useState } from 'react';
import { BookOpen, ClipboardCheck } from 'lucide-react';
import { projectStates,saveProject,saveProjectService,serviceTypes } from '../lib/projects.mjs';
const emptyProject=()=>({title:'',school:'',district:'',topic:'',esepId:'',role:'',status:'active'});
const emptyService=()=>({projectId:'',date:'',type:'TwinSpace desteği',description:'',result:'',evidence:''});
export default function ProjectWorkspace({projects,onChange,services,onServicesChange,ready=true}){
 const [area,setArea]=useState('projects'),[draft,setDraft]=useState(emptyProject),[service,setService]=useState(emptyService),[editing,setEditing]=useState(null),[editingService,setEditingService]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const projectField=(key,label,required=false)=><label className="field">{label}<input id={`project-${key}`} required={required} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>;
 const serviceField=(key,label,multiline=false,required=false)=><label className="field">{label}{multiline?<textarea rows={3} required={required} value={service[key]} onChange={e=>setService({...service,[key]:e.target.value})}/>:<input type={key==='date'?'date':'text'} required={required} value={service[key]} onChange={e=>setService({...service,[key]:e.target.value})}/>}</label>;
 function submitProject(e){e.preventDefault();try{onChange(saveProject(projects,draft,editing||crypto.randomUUID()));setDraft(emptyProject());setEditing(null);setError('');setNotice('Mevcut proje kaydedildi.');}catch(err){setError(err.message);}}
 function submitService(e){e.preventDefault();try{onServicesChange(saveProjectService(services,service,editingService||crypto.randomUUID(),projects));setService(emptyService());setEditingService(null);setError('');setNotice('Projeye verilen hizmet kaydedildi.');}catch(err){setError(err.message);}}
 return <><section className="project-intro"><div><span className="eyebrow">PROJELER VE TWINSPACE</span><h2>Mevcut projeleri ve verilen hizmetleri izleyin</h2><p>Yalnız ESEP’te açılmış projeleri kaydedin; koordinatörlük desteğini tarih ve sonuç bilgisiyle projeye bağlayın.</p></div><span>{projects.length} proje · {services.length} hizmet</span></section>
  <div className="mentor-area-tabs" role="tablist" aria-label="Proje çalışma alanları"><button role="tab" aria-selected={area==='projects'} className={area==='projects'?'active':''} onClick={()=>setArea('projects')}><BookOpen size={19}/> Mevcut Projeler</button><button role="tab" aria-selected={area==='services'} className={area==='services'?'active':''} onClick={()=>setArea('services')}><ClipboardCheck size={19}/> Projeye Verilen Hizmetler</button></div>
  <div className="project-source-note"><b>ESEP kaydı zorunludur.</b> REFİKA bu sürümde canlı veri çekmez; proje kimliği koordinatör tarafından ESEP’te kontrol edilerek yazılır.</div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<output>{notice}</output>}
  {area==='projects'&&<><section className="card project-editor"><div className="card-heading"><h2>{editing?'Projeyi güncelle':'Mevcut proje ekle'}</h2><span className="badge">{projects.length} proje</span></div><form onSubmit={submitProject}><fieldset disabled={!ready} className="project-form">{projectField('title','Proje adı',true)}{projectField('esepId','ESEP proje kimliği',true)}{projectField('school','Projede yer alan okul',true)}{projectField('district','İlçe')}{projectField('topic','Tema / konu')}{projectField('role','Projede rolü',true)}<label className="field">Proje durumu<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{Object.entries(projectStates).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="actions"><button className="primary">Projeyi kaydet</button>{editing&&<button type="button" className="secondary" onClick={()=>{setDraft(emptyProject());setEditing(null);}}>Vazgeç</button>}</div></fieldset></form></section><ProjectList projects={projects} onEdit={project=>{setDraft(project);setEditing(project.id);}}/></>}
  {area==='services'&&<><section className="card project-editor"><div className="card-heading"><h2>{editingService?'Hizmet kaydını güncelle':'Projeye hizmet ekle'}</h2><span className="badge">{services.length} hizmet</span></div>{!projects.length?<p className="notice">Önce “Mevcut Projeler” bölümünden ESEP projesini kaydedin.</p>:<form onSubmit={submitService}><fieldset disabled={!ready} className="project-form"><label className="field">Proje<select required value={service.projectId} onChange={e=>setService({...service,projectId:e.target.value})}><option value="">Seçin</option>{projects.map(project=><option key={project.id} value={project.id}>{project.title} · {project.esepId}</option>)}</select></label>{serviceField('date','Hizmet tarihi',false,true)}<label className="field">Hizmet türü<select value={service.type} onChange={e=>setService({...service,type:e.target.value})}>{serviceTypes.map(type=><option key={type}>{type}</option>)}</select></label>{serviceField('description','Verilen destek / yapılan çalışma',true,true)}{serviceField('result','Elde edilen sonuç',true,true)}{serviceField('evidence','Kanıt veya bağlantı notu',true)}<div className="actions"><button className="primary">Hizmeti kaydet</button>{editingService&&<button type="button" className="secondary" onClick={()=>{setService(emptyService());setEditingService(null);}}>Vazgeç</button>}</div></fieldset></form>}</section><section className="card project-list"><div className="card-heading"><h2>Hizmet geçmişi</h2><span className="badge">{services.length} kayıt</span></div>{!services.length?<p className="muted">Henüz projeye verilen hizmet kaydedilmedi.</p>:<ul>{services.map(item=>{const project=projects.find(p=>p.id===item.projectId);return <li key={item.id}><div><strong>{project?.title||'Proje'} · {item.type}</strong><p>{item.date.split('-').reverse().join('.')} · {item.description}</p><small>Sonuç: {item.result}{item.evidence?` · Kanıt: ${item.evidence}`:''}</small></div><button className="secondary" onClick={()=>{setService(item);setEditingService(item.id);}}>Düzenle</button></li>})}</ul>}</section></>}</>;
}
function ProjectList({projects,onEdit}){return <section className="card project-list"><div className="card-heading"><h2>Mevcut proje listesi</h2><span className="badge">{projects.length} proje</span></div>{!projects.length?<p className="muted">ESEP’te açılmış ilk projeyi kaydedin.</p>:<ul>{projects.map(project=><li key={project.id}><div><strong>{project.title}</strong><p>{project.school}{project.district?` · ${project.district}`:''}</p><small>ESEP: {project.esepId} · {project.role} · {projectStates[project.status]}</small></div><button className="secondary" onClick={()=>onEdit(project)}>Düzenle</button></li>)}</ul>}</section>}
