'use client';
import { useEffect, useMemo, useState } from 'react';
import { Award, Building2, ExternalLink, Plus, Save, Users } from 'lucide-react';
import { qualityLabelSeed } from '../lib/quality-label-seed';
import { etwinningSchoolSeed } from '../lib/etwinning-school-seed';
const KEY='refika-quality-label-years-v1';
const initial={years:[2023,2024,2025,2026],people:qualityLabelSeed,schools:etwinningSchoolSeed};
const personBlank=(year)=>({year,name:'',school:'',project:'',national:'0',european:'0'});
const schoolBlank=(year)=>({year,name:'',schoolId:'',label:'eTwinning Okulu',note:''});
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(!(x&&Array.isArray(x.years)&&Array.isArray(x.people)&&Array.isArray(x.schools)))return initial;const savedPeople=new Set(x.people.map(item=>item.id));const savedSchools=new Set(x.schools.map(item=>item.id));return {...x,years:[...new Set([...x.years,2023,2024,2025,2026])].sort((a,b)=>a-b),people:[...qualityLabelSeed.filter(item=>!savedPeople.has(item.id)),...x.people],schools:[...etwinningSchoolSeed.filter(item=>!savedSchools.has(item.id)),...x.schools]}}catch{return initial}}
export default function QualityLabelWorkspace(){
 const [data,setData]=useState(initial);const [tab,setTab]=useState('people');const [year,setYear]=useState(2026);const [newYear,setNewYear]=useState('2027');const [person,setPerson]=useState(personBlank(2026));const [school,setSchool]=useState(schoolBlank(2026));const [notice,setNotice]=useState('');
 useEffect(()=>{const saved=read();setData(saved);const latest=Math.max(...saved.years);setYear(latest);setPerson(personBlank(latest));setSchool(schoolBlank(latest));},[]);
 const persist=(next)=>{setData(next);localStorage.setItem(KEY,JSON.stringify(next));};
 const summary=useMemo(()=>({people:data.people.filter(x=>x.year===year),schools:data.schools.filter(x=>x.year===year)}),[data,year]);
 const chooseYear=(value)=>{setYear(value);setPerson(personBlank(value));setSchool(schoolBlank(value));setNotice('');};
 function addYear(e){e.preventDefault();const value=Number(newYear);if(value<2020||value>2100)return setNotice('Geçerli bir yıl yazın.');if(data.years.includes(value))return chooseYear(value);persist({...data,years:[...data.years,value].sort((a,b)=>a-b)});chooseYear(value);setNewYear(String(value+1));setNotice(`${value} yılı eklendi.`)}
 function addPerson(e){e.preventDefault();if(!person.name.trim()||!person.school.trim())return setNotice('Kişi ve okul adını doldurun.');const row={...person,id:crypto.randomUUID(),year,national:Number(person.national)||0,european:Number(person.european)||0};persist({...data,people:[...data.people,row]});setPerson(personBlank(year));setNotice(`${row.name}, ${year} yılına kaydedildi.`)}
 function addSchool(e){e.preventDefault();if(!school.name.trim())return setNotice('Okul adını doldurun.');const row={...school,id:crypto.randomUUID(),year};persist({...data,schools:[...data.schools,row]});setSchool(schoolBlank(year));setNotice(`${row.name}, ${year} yılına kaydedildi.`)}
 return <section className="quality-workspace"><header className="quality-hero"><div><span className="eyebrow">Yıllık başarı kaydı</span><h1>Kalite Etiketleri ve eTwinning Okulları</h1><p>Kişilerin etiket sayılarını ve eTwinning Okulu kayıtlarını yıl yıl izleyin.</p></div><Award/></header>
  <div className="quality-links"><a href="https://yegitek.eba.gov.tr/etwinning-kalite-etiketi/" target="_blank" rel="noreferrer">YEĞİTEK Kalite Etiketi Sorgulama <ExternalLink/></a><a href="https://school-education.ec.europa.eu/en/nso-desktop/registrations/schools" target="_blank" rel="noreferrer">ESEP okul kayıtlarını aç <ExternalLink/></a></div>
  <section className="card year-manager"><div><h2>{tab==='schools'?'Dönemler':'Yıllar'}</h2><p>{tab==='schools'?'eTwinning Okulu etiket dönemini seçin.':'Bir yılı seçerek o yıla ait kişi kayıtlarını görüntüleyin.'}</p></div><div className="year-buttons">{data.years.map(y=><button className={year===y?'active':''} onClick={()=>chooseYear(y)} key={y}>{tab==='schools'?`${y}–${y+1}`:y}</button>)}</div><form onSubmit={addYear}><label className="field">{tab==='schools'?'Yeni dönem başlangıcı':'Yeni yıl'}<input type="number" min="2020" max="2100" value={newYear} onChange={e=>setNewYear(e.target.value)}/></label><button className="secondary"><Plus/> {tab==='schools'?'Dönem ekle':'Yıl ekle'}</button></form></section>
  <div className="quality-tabs"><button className={tab==='people'?'active':''} onClick={()=>setTab('people')}><Users/> Öğretmen etiketleri</button><button className={tab==='schools'?'active':''} onClick={()=>setTab('schools')}><Building2/> eTwinning Okulları</button></div>{notice&&<output>{notice}</output>}
  {tab==='people'?<><section className="card quality-entry"><div className="card-heading"><h2>{year} · Yeni kişi kaydı</h2><span className="badge">{summary.people.length} kişi · {summary.people.reduce((n,x)=>n+x.national,0)} ulusal · {summary.people.reduce((n,x)=>n+x.european,0)} Avrupa</span></div><p>Aynı kişinin aynı yıl içindeki bütün projelerinden aldığı etiketlerin toplamını ayrı ayrı yazın.</p><form onSubmit={addPerson}><label className="field">Ad soyad<input required value={person.name} onChange={e=>setPerson({...person,name:e.target.value})}/></label><label className="field">Okul<input required value={person.school} onChange={e=>setPerson({...person,school:e.target.value})}/></label><label className="field">Proje veya proje notu<input value={person.project} onChange={e=>setPerson({...person,project:e.target.value})}/></label><label className="field">Ulusal Kalite Etiketi sayısı<input type="number" min="0" value={person.national} onChange={e=>setPerson({...person,national:e.target.value})}/></label><label className="field">Avrupa Kalite Etiketi sayısı<input type="number" min="0" value={person.european} onChange={e=>setPerson({...person,european:e.target.value})}/></label><button className="primary"><Save/> Kişiyi {year} yılına kaydet</button></form></section><RecordTable type="people" year={year} rows={summary.people}/></>:<><section className="card quality-entry"><div className="card-heading"><h2>{year}–{year+1} · Yeni okul kaydı</h2><span className="badge">{summary.schools.length} okul</span></div><p>ESEP’te doğruladığınız eTwinning Okulu kaydını ilgili döneme ekleyin.</p><form onSubmit={addSchool}><label className="field">Okul adı<input required value={school.name} onChange={e=>setSchool({...school,name:e.target.value})}/></label><label className="field">ESEP okul kimliği<input value={school.schoolId} onChange={e=>setSchool({...school,schoolId:e.target.value})}/></label><label className="field">Etiket / dönem<input value={school.label} onChange={e=>setSchool({...school,label:e.target.value})}/></label><label className="field">Kontrol notu<textarea rows="2" value={school.note} onChange={e=>setSchool({...school,note:e.target.value})}/></label><button className="primary"><Save/> Okulu {year}–{year+1} dönemine kaydet</button></form></section><RecordTable type="schools" year={year} rows={summary.schools}/></>}<YearAnalysis year={year} people={summary.people} schools={summary.schools}/></section>
}
function RecordTable({type,year,rows}){return <section className="card quality-records"><h2>{type==='people'?`${year} Kişi Kayıtları`:`${year}–${year+1} eTwinning Okulu Kayıtları`}</h2>{!rows.length?<p className="empty">Bu yıl için henüz kayıt eklenmedi.</p>:<div className="quality-table-wrap"><table><thead><tr>{type==='people'?<><th>Kişi</th><th>Okul</th><th>Proje/not</th><th>Ulusal</th><th>Avrupa</th></>:<><th>Okul</th><th>ESEP okul kimliği</th><th>Etiket/dönem</th><th>Kontrol notu</th></>}</tr></thead><tbody>{rows.map(x=><tr key={x.id}>{type==='people'?<><td><b>{x.name}</b></td><td>{x.school}</td><td>{x.project||'—'}</td><td>{x.national}</td><td>{x.european}</td></>:<><td><b>{x.name}</b></td><td>{x.schoolId||'—'}</td><td>{x.label}</td><td>{x.note||'—'}</td></>}</tr>)}</tbody></table></div>}</section>}
function YearAnalysis({year,people,schools}){const national=people.reduce((n,x)=>n+Number(x.national||0),0);const european=people.reduce((n,x)=>n+Number(x.european||0),0);return <section className="card year-analysis"><div><span className="eyebrow">Yıl sonu görünümü</span><h2>{year} Analizi</h2><p>Bu yılın kişi, kalite etiketi ve eTwinning Okulu kayıtlarının özeti.</p></div><div className="analysis-cards"><article><Users/><b>{people.length}</b><span>Kayıtlı kişi</span></article><article><Award/><b>{national}</b><span>Ulusal Kalite Etiketi</span></article><article><Award/><b>{european}</b><span>Avrupa Kalite Etiketi</span></article><article><Building2/><b>{schools.length}</b><span>eTwinning Okulu</span></article></div></section>}
