'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Archive, CheckCircle2, ClipboardList, ExternalLink, FileText, Mail, Newspaper, Plus, Save, Upload } from 'lucide-react';
import { createNewsDraft } from '../lib/news-draft.mjs';

const tabs=[['activity','Faaliyet ve haber',Newspaper],['report','Dönem raporu',FileText],['mail','Resmî yazışmalar',Mail],['result','Sonuç takibi',CheckCircle2]];
const samples=[
 {id:'r-1',type:'Faaliyet',title:'İl koordinatörleri çevrim içi bilgilendirme toplantısı',date:'2026-09-10',status:'Haber bekliyor'},
 {id:'r-2',type:'Yazışma',title:'Validasyon talepleri',date:'2026-09-11',status:'Sonuç bekleniyor'},
];
const fmt=v=>v?v.split('-').reverse().join('.'):'Tarih yok';

export default function ReportCorrespondenceWorkspace({tasks=[],events=[]}){
 const [tab,setTab]=useState('activity');
 const [records,setRecords]=useState(samples);
 const [form,setForm]=useState({title:'',date:'',result:'',evidence:'',news:''});
 const [evidenceFiles,setEvidenceFiles]=useState([]);
 const [mail,setMail]=useState({subject:'',recipient:'',body:''});
 const [saved,setSaved]=useState('');
 const [step,setStep]=useState(1);
 const panelRef=useRef(null),evidenceRef=useRef(null);
 useEffect(()=>{try{const x=localStorage.getItem('refika-report-records');if(x)setRecords(JSON.parse(x));const draft=JSON.parse(localStorage.getItem('refika-plan-draft')||'null');if(draft){setForm(v=>({...v,title:draft.title}));setSaved(`${draft.month} faaliyet planındaki “${draft.title}” kayda getirildi. Gerçekleşme tarihi ve sonucu girerek devam edin.`);localStorage.removeItem('refika-plan-draft');}}catch{}},[]);
 const completed=useMemo(()=>[...tasks,...events].filter(x=>x.status==='completed'),[tasks,events]);
 function persist(next){setRecords(next);localStorage.setItem('refika-report-records',JSON.stringify(next));}
 function addActivity(e){e.preventDefault();persist([{id:`r-${Date.now()}`,type:'Faaliyet',title:form.title,date:form.date,status:form.news?'Haber taslağı kaydedildi':'Haber bekliyor',result:form.result,evidence:form.evidence,evidenceFiles,news:form.news},...records]);setSaved(`Faaliyet kaydı${evidenceFiles.length?` ve ${evidenceFiles.length} kanıt dosyasının adı`:''} REFİKA prototipine kaydedildi.`);}
 function prepareNews(){const draft=createNewsDraft(form);if(!draft.ok){setSaved(draft.error);return}setForm({...form,news:draft.text});setSaved('Yapay zekâ destekli haber metni ve Instagram hesapları aşağıdaki taslak alanına getirildi. Henüz kaydedilmedi.');}
 function saveMail(e){e.preventDefault();persist([{id:`r-${Date.now()}`,type:'Yazışma',title:mail.subject,date:new Date().toISOString().slice(0,10),status:'Gönderim öncesi kontrol'},...records]);setSaved('Yazışma taslağı kaydedildi. REFİKA kendiliğinden e-posta göndermez.');}
 function openStep(value){const targets={1:'activity',2:'activity',3:'report',4:'mail',5:'result'};setStep(value);setTab(targets[value]);setSaved('');setTimeout(()=>{panelRef.current?.scrollIntoView({behavior:'smooth',block:'start'});if(value===2)evidenceRef.current?.focus();},80);}
 return <div className="reports-workspace">
  <section className="reports-hero"><div><span>İŞLEMDEN KURUMSAL HAFIZAYA</span><h2>Raporlar ve Yazışmalar</h2><p>Gerçekleşen işi kaydedin, kanıtı tamamlayın, haber ve yazışma taslağını hazırlayın; sonucu aynı kayıtta izleyin.</p></div><Archive/></section>
  <ol className="reports-flow">{['Faaliyeti kaydet','Kanıt ve haberi tamamla','Dönem raporuna ekle','Yazışmayı hazırla','Sonucu kaydet'].map((x,i)=><li key={x}><button type="button" className={step===i+1?'active':''} onClick={()=>openStep(i+1)}><span>{i+1}</span><b>{x}</b></button></li>)}</ol>
  <section className="reports-summary"><div><ClipboardList/><b>{records.filter(x=>x.type==='Faaliyet').length+completed.length}</b><span>Faaliyet kaydı</span></div><div><Newspaper/><b>{records.filter(x=>/Haber/.test(x.status)).length}</b><span>Haber bekliyor</span></div><div><Mail/><b>{records.filter(x=>x.type==='Yazışma').length}</b><span>Yazışma</span></div><div><CheckCircle2/><b>{records.filter(x=>x.status==='Tamamlandı').length}</b><span>Tamamlanan</span></div></section>
  <nav className="reports-tabs" aria-label="Rapor çalışma alanları">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setStep(id==='activity'?1:id==='report'?3:id==='mail'?4:5);setSaved('')}}><Icon/>{label}</button>)}</nav>
  <div ref={panelRef}/>
  {saved&&<p className="reports-success"><CheckCircle2/>{saved}</p>}
  {tab==='activity'&&<section className="card reports-panel"><div className="card-heading"><h2>Faaliyet kaydı ve haber</h2><span className="badge">Gerçekleşen faaliyet üzerinden</span></div><form onSubmit={addActivity} className="reports-form"><label className="field">Faaliyet adı<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="field">Gerçekleşme tarihi<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label className="field reports-wide">Gerçekleşen sonuç<textarea required rows="3" value={form.result} onChange={e=>setForm({...form,result:e.target.value})}/></label><label className="field">Kanıt bağlantısı veya belge notu<input ref={evidenceRef} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})} placeholder="Drive, EBA, haber veya fotoğraf albümü bağlantısı…"/></label><label className="field evidence-upload">Kanıt dosyaları<input type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={e=>setEvidenceFiles(Array.from(e.target.files||[]).map(file=>file.name))}/><span>{evidenceFiles.length?`${evidenceFiles.length} dosya seçildi: ${evidenceFiles.join(`, `)}`:`PDF, Word, Excel veya görsel seçebilirsiniz.`}</span></label><div className="reports-actions"><button type="button" className="secondary" onClick={prepareNews}><Newspaper/> Yapay zekâ ile haber taslağı oluştur</button><button className="primary"><Plus/> Faaliyet kaydını oluştur</button></div>{form.news&&<label className="field reports-wide">Hazırlanan haber taslağı<textarea rows="6" value={form.news} onChange={e=>setForm({...form,news:e.target.value})}/></label>}</form></section>}
  {tab==='report'&&<section className="card reports-panel"><div className="card-heading"><h2>Dönem raporu hazırlık listesi</h2><span className="badge">Kanıtı tamamlanan kayıtlar</span></div><p className="notice">Rapor; planlanan işlerden değil, gerçekleşme tarihi, katılım, sonuç, kanıt ve haber bağlantısı bulunan kayıtlardan hazırlanır.</p><div className="report-period-card"><div><b>2025–2026 / 3. Dönem</b><span>01.07–30.09.2026</span></div><strong>{records.filter(x=>x.type==='Faaliyet').length+completed.length} kayıt</strong><button className="primary" onClick={()=>setSaved('Dönem raporu taslağı hazırlanmak üzere işaretlendi.')}><FileText/> Rapor taslağını hazırla</button></div><div className="yegitek-report-link"><div><b>Resmî rapor girişi</b><p>REFİKA’daki rapor ve kanıtları kontrol ettikten sonra YEĞİTEK EBA Rapor Modülüne geçin.</p></div><a className="primary" href="https://yegitek.eba.gov.tr/etwinning-rapor/" target="_blank" rel="noreferrer">YEĞİTEK EBA Rapor Modülünü Aç <ExternalLink/></a></div><p className="muted">REFİKA resmî modüle otomatik veri göndermez. Son kontrol ve kayıt işlemi il koordinatörü tarafından YEĞİTEK EBA’da yapılır.</p></section>}
  {tab==='mail'&&<section className="card reports-panel"><div className="card-heading"><h2>Resmî yazışma taslağı</h2><span className="badge">Gönderim koordinatör onayıyla</span></div><form onSubmit={saveMail} className="reports-form"><label className="field">Konu<input required value={mail.subject} onChange={e=>setMail({...mail,subject:e.target.value})}/></label><label className="field">Alıcı birim<input required value={mail.recipient} onChange={e=>setMail({...mail,recipient:e.target.value})}/></label><label className="field reports-wide">E-posta metni<textarea required rows="8" value={mail.body} onChange={e=>setMail({...mail,body:e.target.value})}/></label><div className="reports-wide reports-mail-note"><Upload/>Eklenmesi gereken liste ve kanıtları gönderimden önce kontrol edin.</div><div className="reports-wide reports-actions"><button className="primary"><Save/> Taslağı kaydet</button></div></form></section>}
  {tab==='result'&&<section className="card reports-panel"><div className="card-heading"><h2>Gönderimler ve sonuçlar</h2><span className="badge">{records.length} kayıt</span></div><div className="reports-table"><div className="reports-row head"><b>Kayıt</b><b>Tarih</b><b>Durum</b><b>İşlem</b></div>{records.map(x=><div className="reports-row" key={x.id}><div><b>{x.title}</b><small>{x.type}</small></div><span>{fmt(x.date)}</span><span className="badge">{x.status}</span><button className="text-link" onClick={()=>{persist(records.map(r=>r.id===x.id?{...r,status:'Tamamlandı'}:r));setSaved('Sonuç tamamlandı olarak kaydedildi.')}}>Sonucu kaydet</button></div>)}</div></section>}
  <p className="reports-principle">REFİKA taslak hazırlar ve süreci hatırlatır; doğruluk kontrolü, resmî gönderim ve yayımlama kararı il koordinatöründedir.</p>
 </div>;
}
